---
version: '3.4'

services:
  vthumb:
    image: markkimsal/video-thumbnailer:1.2.0
    build:
        context: .
        dockerfile: Dockerfile
    ports:
       - 9999:80
    environment:
       - DOMAINS=github.com
